### ISSUE TITLE
Inconsistency in label derivation if one or multiple terms is present

### ISSUE THREAD

**Issue by mikevacany** [whileman133/fastZ#1]
Thank you for great tool.

I encountered weird behavior for the nested impedance expression label naming which is dependent on the number (one or more) of terms in expression.

This example gives error.
```
Zball = (R('p',v=1.8e-3) + L('p',v=64e-12))["ball"]
Zpkg = (Zball // Zball // Zball // Zball)["pkg"]
Zin = ( Zpkg // ( C('d',v=1e-9) + R('d',v=40e-3))['die'] )['in']
Ztrg = (R('trg',v=600e-3)) ['trg']
ff = np.logspace(7, 10, 1000)
fig, ax = bodez(Zin, ff=ff, zlines='Zin:100e6 Zdie Zpkg', refzlines='Lp Cd') # Rp Rd
```
```
File "C:\Users\a5130372\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastz\core.py", line 215, in subz
    raise KeyError(f"Could not locate impedance with the label '{label}' within '{self}'.")
KeyError: "Could not locate impedance with the label 'Zpkg' within 'Zin:(Zball:(Rp[0.0018Ω] + Lp[6.4e-11H]) || Zball:(Rp[0.0018Ω] + Lp[6.4e-11H]) || Zball:(Rp[0.0018Ω] + Lp[6.4e-11H]) || Zball:(Rp[0.0018Ω] + Lp[6.4e-11H]) || Zdie:(Cd[1e-09F] + Rd[0.04Ω]))'."
```

On the other hand, this is ok - changing just Zpkg = (Zball)["pkg"]:
```
Zball = (R('p',v=1.8e-3) + L('p',v=64e-12))["ball"]
Zpkg = (Zball)["pkg"]
Zin = ( Zpkg // ( C('d',v=1e-9) + R('d',v=40e-3))['die'] )['in']
Ztrg = (R('trg',v=600e-3)) ['trg']
ff = np.logspace(7, 10, 1000)
fig, ax = bodez(Zin, ff=ff, zlines='Zin:100e6 Zdie Zpkg', refzlines='Lp Cd') # Rp Rd
```

Is there a way to keep the label naming consistent?

**Comment by whileman133** [comment]
@mikevacany I was able to reproduce this issue and put out an update in v1.0.0 that I believe fixes it (if not, please reply).  Thanks for reporting this.

Details in case anyone is interested: Issue in the __floordiv__ (//) and __add__ (+) methods in the abstract Z class.  Connecting a ParallelZ/SeriesZ in parallel/series with another element originally merged both elements into a single ParallelZ/SeriesZ, which corrupted the subscript.  Merging is no longer performed when the element has a non-blank subscript.  All unit tests passing.
